### ISSUE TITLE
[EPIC] Levantar Wollok Game desde el CLI

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok-ts-cli#33]
Alguna estrategia charlada hoy:

- [ ] Separar React de P5 (el dibujador) , de el Environment (wollok-ts). Hoy el proyecto https://github.com/uqbar-project/wollok-game-web separa React de lo demás, pero hay que separar más todavía. 
- [ ] Eso me va a permitir poder construir un **cliente** que **sólo dibuje** y lo ideal es que la **evaluation esté corriendo en el CLI, el servidor**.
- [ ] Esto va a permitir luego poder manipular el estado del game desde el CLI y hacer cosas como tener el diagrama dinámico.
- [ ] Quizás una comunicación entre ambos usando socket io.
