### ISSUE TITLE
[EPIC] Mejoras al Diagrama Dinámico

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts-cli#69]
Ahora que estamos mejorando el Diagrama Dinámico, una épica con todas las mejoras.

Actualmente se ve así:
![image](https://github.com/uqbar-project/wollok-ts-cli/assets/18614957/b196edde-0dbd-4323-bd4f-02e2762f49a3)

- [x] Renombrar `List#asdfg` -> `a List` o `un/a List` #82 
- [x] Teniendo dos (o más) referencias superpuestas solo se muestra una https://github.com/uqbar-project/wollok-ts-cli/issues/68
- [x] Agregarles el índice a las listas.  https://github.com/uqbar-project/wollok-ts-cli/pull/82
  - [x] En Xtext creo que además todas las colecciones (List y Set) se mostraban en línea punteada (qué piensan?).
- [x] Que se vean mejor las flechas, ahora están muy claras. Tal vez convenga hacerlas más gruesas también.
- [x] #73
- [x] Diferenciar las referencias de variables y constantes #59 
- [x] #70
- [x] #71
  - Darle una iterada a los colores / formas de los objetos (revisar XText, Dodino hizo un laburo arduo y fantástico encontrando colores, lo que incluía también diferenciaciones para distintos tipos de daltonismo).
    - Distintos themes (var https://colorhunt.co/)
    - Control del tamaño de la font / UI en general
  - En la imagen de acá, las palabras `true` y `false` no se leen bien
  - Los objetos de las colecciones los haría más chicos que el resto (?
  - ~~Rectángulos para los strings, así entran cómodos~~. _Alf:_ Me gusta más la forma redonda para todos los objetos, se puede quizás jugar con el tamaño o el borde para diferenciar. Es cómodo para explicar dinámico vs estático que el diagrama dinámico tenga cosas redondas (u ovaladas) versus lo cuadrado/rectangular del diag de clases. Bah, además de cómodo me gusta la metáfora que instancia es redondo y clase es cuadrado.
  - ~~Un color particular para los objetos del proyecto (no lang)~~. _Alf:_ En ese sentido, que los objetos "primitivos" o los que vienen dados tengan una forma parecida a un objeto propio me parece una buena decisión didáctica: al fin y al cabo todos son objetos y entienden mensajes. Si los objetos que le alumne no puede tunearse quiere que sean distintos, podemos jugar con el tamaño (como el ejemplo de achicar el objeto de la colección) y/o el grosor del borde.

**Comment by asanzo** [comment]
- Me gusta más la forma redonda para todos los objetos, se puede quizás jugar con el tamaño o el borde para diferenciar.  Es cómodo para explicar dinámico vs estático que el diagrama dinámico tenga cosas redondas (u ovaladas) versus lo cuadrado/rectangular del diag de clases. Bah, además de cómodo me gusta la metáfora que instancia es redondo y clase es cuadrado.

- En ese sentido, que los objetos "primitivos" o los que vienen dados tengan una forma parecida a un objeto propio me parece una buena decisión didáctica: al fin y al cabo todos son objetos y entienden mensajes.  Si los objetos que le alumne no puede tunearse quiere que sean distintos, podemos jugar con el tamaño (como el ejemplo de achicar el objeto de la colección) y/o el grosor del borde.
- Dodino hizo un laburo arduo y fantástico encontrando colores, lo que incluía también diferenciaciones para distintos tipos de daltonismo, yo aprovecharía a reusar ese laburo.
- Les amo, los sigo desde cemento, la radio está re buena,  somos campeones y espero que lo sea muchos años, chau pibe.

**Comment by ivojawer** [comment]
### Cosas que agregaria a la epica
1. Mejorar el sync, mientras lo probaba habia inconsistencias (creo que el caso mas reproducible es cuando cambiaba algo en wollok y tiraba un `:r`) ademas estoy SEGURO de que un schedule/onTick romperia todo
2. Mantener la forma del diagrama al updatearlo, esto se que lo habias revisado Rasta, tal vez es imposible pero verdaderamente es muy molesto (pensando mas en un contexto de clase) que te reordene todo cada vez que detecta un cambio.

### Otros

- Acuerdo fuertemente con @asanzo, que los objetos primitivos se vean parecidos a los propios me parece re importante. En lo personal no me molestaria mientras todos mantengan una forma ovalada, pero es super discutible y habria que probarlo para ver como se siente.
- Peco de ignorante en accesibilidad pero sumado al laburo de dodine algunas cosas que podriamos agregar son
   - Distintos themes
   - Control del tamaño de la font / UI en general

**Comment by guillep** [comment]
> * Hay que revisar los colores / formas de los objetos (revisar XText). Tiro algunas ideas ahora:

https://colorhunt.co/

**Comment by PalumboN** [comment]
AMO LES a los 3. Ahí updatié la descripción del issue para que esté todo junto 👍 

> estoy SEGURO de que un schedule/onTick romperia todo

Esto lo estoy poniendo en este issue https://github.com/uqbar-project/wollok-ts-cli/issues/43 sobre mezclar Game y el REPL.

**Comment by fdodino** [comment]
groso!

Una cosa que recién puse en Discord y lo dejo por acá, creo que:

1- Se puede armar una configuración default y que se pueda cambiar en los settings del proyecto ts-cli
2- Yo quiero que todos los labels estén adentro del nodo. Y cuando la longitud es grande lo que yo haría es lo mismo 

![image](https://github.com/uqbar-project/wollok-ts-cli/assets/4549002/d0f92fac-2c84-49d7-921d-cf6f4a028669)

**Comment by fdodino** [comment]
@asanzo @ivojawer @PalumboN cierro el ticket porque están resueltos todos estos issues y lo que nos queda voy a crear otra épica
